### ISSUE TITLE
[BUG][WEBJS] - Issue in posting to /api/sendVideo

### ISSUE THREAD

**Issue by Souhaibahar** [allburov/whatsapp-http-api#328]
Hello, 
I'm having issue on the endpoint sendVideo

![image](https://github.com/devlikeapro/whatsapp-http-api/assets/43727808/21a845ae-3087-415b-bf72-a9987989dfaa)

**Version**
{
  "version": "2029.10.29",
  "engine": "WEBJS",
  "tier": "PLUS",
  "browser": "/usr/path/to/bin/google-chrome"
}

this the request i'm sending {
  "chatId": "212661768542@c.us",
  "file": {
    "mimetype": "video/mp4",
    "filename": "funnyfastvideo.mp4",
    "url": "https://generator-pipeline-api-test.azurewebsites.net/media/fCN9yyJ9a3cj0_yBUW90EIAXL4c232JTnRBbH4i2_eRgz9XzDVmIuEII6Q98cycafUiky0ZvuVQ_3RKSRS3A==.mp4"
  },
  "caption": "",
  "session": "newuser"
}

and there is no response 
it stays like that , i tried with many different video links and to send to different users 

![image](https://github.com/devlikeapro/whatsapp-http-api/assets/43727808/7699b98a-41ea-4de4-8bf2-8b75e8403eb9)

and then after waiting long the response 
499Undocumented | Error: response status is 499

![image](https://github.com/devlikeapro/whatsapp-http-api/assets/43727808/66eebf87-8b94-4a70-ae70-b9fb7c2f5141)

please advice as soon as possible ,
Thank you so much

**Comment by devlikepro** [comment]
Fixed in `2024.5.6`!

Try first the example payload from https://waha.devlike.pro/docs/how-to/send-messages/#send-video-imagesversionspluspng

```json
{
  "session": "default",
  "chatId": "11111111111@c.us",
  "caption": "Watch this video!",
  "file": {
    "mimetype": "video/mp4",
    "filename": "video.mp4",
    "url": "https://github.com/devlikeapro/whatsapp-http-api/raw/core/examples/video.mp4"
  }
}
```


Personal TY for such detailed report! :heart: 

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by MadhabaPatra** [comment]
Hi @devlikepro , Still getting same error. I am using latest version (2024.5.7) of devlikeapro/whatsapp-http-api-plus:arm

**Comment by devlikepro** [comment]
Sorry, we had to revert the solution, it causes sometime "scan qr" issues. Looking for a way to fix it!

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by MadhabaPatra** [comment]
Sure @devlikepro  , 
Thanks for quick reply. Please update here once you fixed.

**Comment by Thiagomleite** [comment]
I need to send videos, please fix this as soon as possible.

**Comment by willpexero** [comment]
Please fix this problem to send videos using this API. I really need this feature again

**Comment by cadduroleta** [comment]
Please fix this problem to send videos using this API. I really need this feature again

**Comment by joseamonteironeto** [comment]
Please fix that problem :( Really need it...

**Comment by cadduroleta** [comment]
Could you please address this issue so I can resume sending videos through this API? It's a crucial feature for me.

**Comment by Lucasvico1** [comment]
Please fix that problem :( Really need it...

**Comment by brunoskiner** [comment]
if you could fix this issue so that i could send videos through api it will really be helpful for me and a lot of people

**Comment by ANACAROLINA1089** [comment]
Could you fix the video API? I'm having problems when I try to send a video.

**Comment by rafaelboav** [comment]
I need to send videos via API. could you please fix this issue?

**Comment by allburov** [comment]
Fine, fine, just stop spamming :D 

Added a temporary solution in **WAHA Plus** `2024.5.9`

---
https://waha.devlike.pro/docs/how-to/send-messages/#send-video-imagesversionspluspng

⚠️ **WEBJS** (default) engine notes for sending videos ⚠️
- 💡 If you're experiencing **"forever loading" issue** ([#321](https://github.com/devlikeapro/whatsapp-http-api/issues/321), [#328](https://github.com/devlikeapro/whatsapp-http-api/issues/328)) - set up `WAHA_WEBJS_WEB_VERSION=2.2412.54-videofix` environment variable:

```bash
docker run -it -p 3000:3000/tcp -e WAHA_WEBJS_WEB_VERSION=2.2412.54-videofix devlikeapro/whatsapp-http-api-plus:chrome
```

---

I don't close the issue, because it requires additional actions right now. When we added "by default" for all session - we'll close the issue and remove the note


[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by allburov** [comment]
:point_up: 
@Thiagomleite 
@willpexero
@joseamonteironeto
@cadduroleta
@Lucasvico1
@brunoskiner
@ANACAROLINA1089
@rafaelboav

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by joseamonteironeto** [comment]
> ☝️ @Thiagomleite @willpexero @joseamonteironeto @cadduroleta @Lucasvico1 @brunoskiner @ANACAROLINA1089 @rafaelboav
> 
> [![patron:PRO](https://camo.githubusercontent.com/53c8c17e54974d30f0938bed9c2aa4e5c7dc7bc776296a6776840124e4086a04/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f706174726f6e2d50524f2d313838613432)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)



> Fine, fine, just stop spamming :D
> 
> Added a temporary solution in **WAHA Plus** `2024.5.9`
> 
> https://waha.devlike.pro/docs/how-to/send-messages/#send-video-imagesversionspluspng
> 
> ⚠️ **WEBJS** (default) engine notes for sending videos ⚠️
> 
> * 💡 If you're experiencing **"forever loading" issue** ([#321](https://github.com/devlikeapro/whatsapp-http-api/issues/321), [#328](https://github.com/devlikeapro/whatsapp-http-api/issues/328)) - set up `WAHA_WEBJS_WEB_VERSION=2.2412.54-videofix` environment variable:
> 
> ```shell
> docker run -it -p 3000:3000/tcp -e WAHA_WEBJS_WEB_VERSION=2.2412.54-videofix devlikeapro/whatsapp-http-api-plus:chrome
> ```
> 
> I don't close the issue, because it requires additional actions right now. When we added "by default" for all session - we'll close the issue and remove the note
> 
> [![patron:PRO](https://camo.githubusercontent.com/53c8c17e54974d30f0938bed9c2aa4e5c7dc7bc776296a6776840124e4086a04/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f706174726f6e2d50524f2d313838613432)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

It works! Thanks :)

**Comment by devlikepro** [comment]
Let's close the issue because it has a workaround. When we moved to new whatsapp (when they released it) - it'll work by default

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by egbertomonteiro** [comment]
Im facing the same problem. Version: 2024.6.7 no workaround applied.
I updated to the latest version a few weeks ago to resolve the random session crashes. If I apply this workaround, will I have any downside?

**Comment by devlikepro** [comment]
> If I apply this workaround, will I have any downside?

Nope, it's regular version, but with the fix!

We're working on fixiing it completely, hopefully soon :crossed_fingers: 

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
